### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by SinTh0r4s** [SinTh0r4s/ExampleMod1.7.10#2]
- [ ] accessTransformerFile parameter + example
- [ ] Support core mod (requires fully qualified name)
- [ ] Somehow link the normal `FMLCorePluginContainsFMLMod` and `loadNormalModAfterApplingMixins` into one parameter

After Kotlin conversion:

- [ ] Provide function to check if file exists for fully qualified name
- [ ] Universal manifest task
- [ ] Run once at begin function:
   - Move java check there
   - Move GT timeout protection there
   - Check new parameters for existing and ask user to modify build.properties if missing
   - Check parameters for validity if possible (mostly: doe specified field exist?)

**Comment by TheElan** [comment]
[  ] Convert this project into [github template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) and add info on [how to start new repository from a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) into readme
[  ] Fork [IDEA Minecraft plugin](https://plugins.jetbrains.com/plugin/8327-minecraft-development) which has [MIT License](https://github.com/minecraft-dev/MinecraftDev/blob/dev/license.txt) and add support for this template

**Comment by SinTh0r4s** [comment]
- [ ] Actually test it on a couple different projects. Do any issues pop up?

**Comment by basdxz** [comment]
- [ ] Requires at least one git tag or it crashes gradle sync
- [ ] Gradle tag replacement doesn't work with 'Minecraft Client'

**Comment by SinTh0r4s** [comment]
Can we test commits on the build script on production repositories and compare before and after? Validate them manually before (refmaps for Mixins exist, MANIFEST entries are valid and so on). Then we don't need to create our own test repos. Might be less stable though

**Comment by TheElan** [comment]
Remaining points should probably endup as separate issues, so it's easier to see what's requires attention
